os: linux
dist: bionic

language: go

go:
  - "1.13"

services:
  - docker

env:
  - GOFLAGS=-mod=vendor

stages:
  - Unit tests
  - Acceptance tests

jobs:
  include:
    - name: Unit tests
      stage: Unit tests
      script:
        - make test
        - make vet
        - make website-test
    - name: Acceptance tests
      stage: Acceptance tests
      env:
        - KIND_VERSION=0.7.0
      install:
        - curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64 && chmod +x ./kind
      before_script:
        - ./kind create cluster --name dev
      script:
        - make testacc
